name: Standard

on: [pull_request, push, workflow_dispatch]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Check types
        run: npm run type-check
      - name: Check format
        run: npm run format-check
      - name: Check lint
        run: npm run lint-check
      - name: Test
        run: npm run test
